#!/bin/bash

# 4 Stages of Expansions

# Stage 1: Brace Expansion
# Stage 2:
#     Parameter Expansion
#     Arithmetic Expansion
#     Command Substitution
#     Tilde Expansion   

# Stage 3: Word Splitting
# Stage 4: Globbing   


# NOT WORKING
# x=10
# echo {1..$x}


# WORKING FOLLOWING PRIORITIES
name=adrian
echo $name has {1..5} computers and $(( 3 + 1 )) keyboards

# TRICKY
name=file
echo $name{1..3}.txt

# Word splitting example
echo "${IFS@Q}"

numbers="1 2 3 4 5"
#numbers="1,2,3,4,5"
#IFS=","
echo $numbers
echo "$numbers"


# Globbing examples
ls month_*.txt
ls month_??.txt
ls month_[1-12].txt



