#!/bin/bash

# 4 Stages of Expansions

# Stage 1: Brace Expansion
# Stage 2:
#     Parameter Expansion
#     Arithmetic Expansion
#     Command Substitution
#     Tilde Expansion   

# Stage 3: Word Splitting
# Stage 4: Globbing   


# NOT WORKING
# x=10
# echo {1..$x}


# WORKING FOLLOWING PRIORITIES
name=adrian
echo $name has {1..5} computers and $(( 3 + 1 )) keyboards

# TRICKY
name=file
echo $name{1..3}.txt
# 4 Stages of Expansions

# Stage 1: Brace Expansion
# Stage 2:
#     Parameter Expansion
#     Arithmetic Expansion
#     Command Substitution
#     Tilde Expansion   

# Stage 3: Word Splitting
# Stage 4: Globbing   
 
